django/django/mysite/blog/urls.py
from django.urls import include, path

from . import views


urlpatterns = [
    
    path("", views.PostList.as_view(), name="home"),
    # path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path("<slug:slug>/", views.post_detail, name="post_detail"),
    
]

django/django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('blog.urls')),

]

django/django/mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User


STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

django/django/mysite/blog/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name", "body")

django/django/mysite/blog/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic

from .models import Post
from .forms import CommentForm


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by("-created_on")
    template_name = "index.html"
    paginate_by = 3


# class PostDetail(generic.DetailView):
#     model = Post
#     template_name = 'post_detail.html'


def post_detail(request, slug):
    template_name = "post_detail.html"
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True).order_by("-created_on")
    new_comment = None
    # Comment posted
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(
        request,
        template_name,
        {
            "post": post,
            "comments": comments,
            "new_comment": new_comment,
            "comment_form": comment_form,
        },
    )

django/django/mysite/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>MyBlog</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <meta name="google" content="notranslate" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
    {% load static %}
    <link rel="stylesheet" href="../static/css/style.css"/>

</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">MyBlog</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="#" id="aboutBtn">About</a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="#" id="policyBtn">Policy</a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="#" id="contactBtn">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    <!-- Content Goes Here -->
    {% endblock content %}

    <!-- About Popup -->
    <div id="aboutPopup" class="popup">
        <div class="popup-content">
            <span class="close">&times;</span>
            <h2>About</h2>
            <p style="text-align: justify;">Welcome to MyBlog, a space dedicated to all things development and technology! 
                I'm Sandip, a passionate computer science engineer with a deep enthusiasm for 
                software development, cutting-edge technology, and the ever-evolving landscape of
                 the digital world. This blog is a culmination of my experiences, insights, and ongoing
                  journey in the field of computer science. <a href="#">Click Here</a> to know more about MyBlog</p>
        </div>
    </div>

    <!-- Policy Popup -->
    <div id="policyPopup" class="popup">
        <div class="popup-content">
            <span class="close">&times;</span>
            <h2>Policy</h2>
            <p style="text-align: justify;">We value your participation and are committed to protecting your privacy and intellectual property while ensuring the quality
                 and integrity of our content. Should you have any questions or need further assistance, 
                 please do not hesitate to contact us at <a href="mailto:i@imsandip.tech">i@imsandip.tech</a>. Thank you for being an integral
                  part of our community and for helping us uphold these standards. Together, we can foster a
                   space that encourages learning, sharing, and growth for everyone involved.</p>
        </div>
    </div>

    <!-- Contact Popup -->
    <div id="contactPopup" class="popup">
        <div class="popup-content">
            <span class="close">&times;</span>
            <h2>Contact</h2>
            <p>Name : Sandip Das</p>
            <p>Email : i@imsandip.tech</p>
            <p>Call : 860****951</p>
            <p>If you want to visit my portfolio <a href="https://imsandip.tech" target="_blank">click here</a></p>
        </div>
    </div>

    <!-- Footer -->
    <footer class="py-3 bg-grey">
        <p class="m-0 text-dark text-center ">Copyright &copy; MyBlog</p>
    </footer>

    <script src="{% static 'js/popup.js' %}"></script>



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39jDZvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

django/django/mysite/templates/index.html
{% extends "base.html" %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<div class="masthead" style="background-color: rgb(76, 73, 85);">

    <div class="container">
        <div class="row">
            <div class=" col-md-5">
                <div class="heading">
                    <h3 class="heading my-3 mt-3 text-white"> Welcome to myBlog Site</h3>
                    <p class="text-light">Let's Explore &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-11 mt-5">
            {% for post in post_list %}
            <div class="card mb-5" style="background-color: rgb(212, 240, 231);">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{%endblock%}

django/django/mysite/templates/post_detail.html
{% extends 'base.html' %}
 {% block content %}<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top"style="background-color: rgb(212, 240, 231);paddng:50px;"> 
     <div class="card-body">
        <h1>{% block title %} {{ post.title }} {% endblock title %}</h1> 
       <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ post.content | safe }}</p> 
     </div>    </div> 

   <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments --> 
       <h2>{{ comments.count }} comments</h2>
        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold"> 
           {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
        </div>
        {% endfor %}
      </div> 
   </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is posted.
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}